[debug] [2025-02-22T19:14:16.454Z] ----------------------------------------------------------------------
[debug] [2025-02-22T19:14:16.465Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\aryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2025-02-22T19:14:16.465Z] CLI Version:   13.31.2
[debug] [2025-02-22T19:14:16.465Z] Platform:      win32
[debug] [2025-02-22T19:14:16.465Z] Node Version:  v22.12.0
[debug] [2025-02-22T19:14:16.466Z] Time:          Sun Feb 23 2025 00:44:16 GMT+0530 (India Standard Time)
[debug] [2025-02-22T19:14:16.466Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-02-22T19:14:16.766Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2025-02-22T19:14:16.767Z] > authorizing via signed-in user (aryamishra212001@gmail.com)
[debug] [2025-02-22T19:14:16.767Z] [iam] checking project flixgpt-98f8a for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2025-02-22T19:14:16.769Z] Checked if tokens are valid: false, expires at: 1740229772308
[debug] [2025-02-22T19:14:16.769Z] Checked if tokens are valid: false, expires at: 1740229772308
[debug] [2025-02-22T19:14:16.769Z] > refreshing access token with scopes: []
[debug] [2025-02-22T19:14:16.772Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2025-02-22T19:14:16.772Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2025-02-22T19:14:38.009Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------822094094226629876694314","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4009:82e::200a:443
[error] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-02-22T19:14:38.011Z] [iam] error while checking permissions, command may fail: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-02-22T19:14:38.013Z] Checked if tokens are valid: false, expires at: 1740229772308
[debug] [2025-02-22T19:14:38.013Z] Checked if tokens are valid: false, expires at: 1740229772308
[debug] [2025-02-22T19:14:38.013Z] > refreshing access token with scopes: []
[debug] [2025-02-22T19:14:38.014Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2025-02-22T19:14:38.014Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2025-02-22T19:14:59.080Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------634273854981863428339498","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4009:82e::200a:443
[error] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-02-22T19:14:59.082Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-02-22T19:15:04.119Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\aryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:269:49)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-02-22T19:16:44.349Z] ----------------------------------------------------------------------
[debug] [2025-02-22T19:16:44.353Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\aryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login --reauth
[debug] [2025-02-22T19:16:44.354Z] CLI Version:   13.31.2
[debug] [2025-02-22T19:16:44.354Z] Platform:      win32
[debug] [2025-02-22T19:16:44.354Z] Node Version:  v22.12.0
[debug] [2025-02-22T19:16:44.354Z] Time:          Sun Feb 23 2025 00:46:44 GMT+0530 (India Standard Time)
[debug] [2025-02-22T19:16:44.355Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=546910822&redirect_uri=http%3A%2F%2Flocalhost%3A9005&login_hint=aryamishra212001%40gmail.com
[info] 
[info] Waiting for authentication...
[debug] [2025-02-22T19:17:46.238Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2025-02-22T19:17:46.239Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2025-02-22T19:18:07.334Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------172099287651827429429119","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 2404:6800:4003:c04::54:443
[debug] [2025-02-22T19:18:07.334Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (C:\Users\aryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:261:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[error] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-02-22T19:18:07.351Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[debug] [2025-02-22T19:18:07.352Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"6785aa46-807e-4782-8e56-4f2fda2c5201"}
[debug] [2025-02-22T19:18:30.893Z] ----------------------------------------------------------------------
[debug] [2025-02-22T19:18:30.897Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\aryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2025-02-22T19:18:30.898Z] CLI Version:   13.31.2
[debug] [2025-02-22T19:18:30.898Z] Platform:      win32
[debug] [2025-02-22T19:18:30.898Z] Node Version:  v22.12.0
[debug] [2025-02-22T19:18:30.899Z] Time:          Sun Feb 23 2025 00:48:30 GMT+0530 (India Standard Time)
[debug] [2025-02-22T19:18:30.899Z] ----------------------------------------------------------------------
[debug] 
[info] Already logged in as aryamishra212001@gmail.com
[debug] [2025-02-22T19:18:41.261Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\aryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:269:49)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-02-22T19:23:59.581Z] ----------------------------------------------------------------------
[debug] [2025-02-22T19:23:59.586Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\aryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2025-02-22T19:23:59.587Z] CLI Version:   13.31.2
[debug] [2025-02-22T19:23:59.587Z] Platform:      win32
[debug] [2025-02-22T19:23:59.587Z] Node Version:  v22.12.0
[debug] [2025-02-22T19:23:59.587Z] Time:          Sun Feb 23 2025 00:53:59 GMT+0530 (India Standard Time)
[debug] [2025-02-22T19:23:59.588Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-02-22T19:23:59.885Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2025-02-22T19:23:59.885Z] > authorizing via signed-in user (aryamishra212001@gmail.com)
[debug] [2025-02-22T19:23:59.886Z] [iam] checking project flixgpt-98f8a for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2025-02-22T19:23:59.888Z] Checked if tokens are valid: false, expires at: 1740229772308
[debug] [2025-02-22T19:23:59.888Z] Checked if tokens are valid: false, expires at: 1740229772308
[debug] [2025-02-22T19:23:59.888Z] > refreshing access token with scopes: []
[debug] [2025-02-22T19:23:59.891Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2025-02-22T19:23:59.891Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2025-02-22T19:24:21.102Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------292442296346487980218325","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4002:82f::200a:443
[error] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-02-22T19:24:21.104Z] [iam] error while checking permissions, command may fail: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-02-22T19:24:21.105Z] Checked if tokens are valid: false, expires at: 1740229772308
[debug] [2025-02-22T19:24:21.105Z] Checked if tokens are valid: false, expires at: 1740229772308
[debug] [2025-02-22T19:24:21.106Z] > refreshing access token with scopes: []
[debug] [2025-02-22T19:24:21.107Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2025-02-22T19:24:21.107Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2025-02-22T19:24:42.154Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------772165288257111460975051","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4002:82f::200a:443
[error] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-02-22T19:24:42.156Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-02-22T19:24:47.180Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\aryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:269:49)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[error] 
[error] Error: An unexpected error has occurred.
